### ISSUE TITLE
Scope bracket removal not working

### ISSUE THREAD

**Issue by Aditeya** [Cassin01/rcz#10]
I've tried the new build, but bracket removal doesn't seem to work. 
I think [main.rs:103](https://github.com/Cassin01/rcz/blob/main/src/main.rs#L103) should match under scope.

**Comment by Cassin01** [comment]
Sorry, I was not sure what you mean. Are you saying that "if the value of the format is `"{type}: { }\n{ }foo"`, then the output will be `"\nfix: \nfoo"` "?

**Comment by Aditeya** [comment]
The format is the default format:

```toml
format = '''
{type}{scope}: {emoji}{subject}
{body}
{footer}'''
```
![image](https://user-images.githubusercontent.com/22963960/215642359-22e37959-bbdd-4633-803c-77ce91bd6111.png)

Inputting a space makes the scope optional so I don't have to delete the brackets.

**Comment by Cassin01** [comment]
I
